#!/bin/bash
#echo $1


#option="${1}" 
#case ${option} in "--v") echo "File name...."y;; 
#"--run") echo "Dir name is ...";;
#esac 

option="${1}"
case ${option} in  "--v") git tag;;
"--run") ./master_shell.sh;;
esac

